first attempts , wrote coments
BohdanPotapchuk/gallery-star pull request #1
Opened 2022-04-14 08:45 UTC by BohdanPotapchuk

2022-04-14 09:15 UTC, stirgin requested changes

2022-04-14 09:15 UTC, stirgin commented on main.js
>    thumbBar.appendChild(newImage);
это часть кода выглядит как часть ответственная за  создание и добавление картинки в панель изображений
ее было бы неплохо вынести в отдельную функцию

2022-04-14 09:15 UTC, stirgin commented on main.js
>    thumbBar.appendChild(newImage);
где путь к картинке мы передаем в эту функцию как параметр

2022-04-14 09:15 UTC, stirgin commented on main.js
> +const a = ['images/pic1.jpg','images/pic2.jpg','images/pic3.jpg','images/pic4.jpg','images/pic5.jpg']
смотри все пути у тебя содержат одинаковую локацию  это папка "images" и по сути одинаковое имя "pic"

вынеси эту особенность в отдельную константу
и еще одну константу для расширения: в нашем случаем это  ".jpeg"

2022-04-14 09:18 UTC, stirgin commented on main.js
> +const a = ['images/pic1.jpg','images/pic2.jpg','images/pic3.jpg','images/pic4.jpg','images/pic5.jpg']
обрати внимание что у путей к картинке только одно отличие :)

можно использовать интерполяцию строк или вынести путь как шаблон (с этим ты уже сталкивался)

2022-04-15 09:38 UTC, BohdanPotapchuk commented on main.js
> +const a = ['images/pic1.jpg','images/pic2.jpg','images/pic3.jpg','images/pic4.jpg','images/pic5.jpg']
Тоесть вот это задание :
    В каждой итерации цикла замените значение-заполнитель xxx строкой, которая 
    будет равна пути к изображению в каждом случае. Мы устанавливаем значение 
    атрибута src для этого значения в каждом случае. Имейте в виду, что в каждом 
     случае изображение находится внутри каталога изображений, а его имя - pic1.jpg, 
     pic2.jpg и т.д.
     
 `images/pic${selectedPic}.jpg` - "ххх строка ,которая 
    будет равна пути к изображению в каждом случае" ,верно?

2022-04-15 14:01 UTC, stirgin commented on main.js
> +const a = ['images/pic1.jpg','images/pic2.jpg','images/pic3.jpg','images/pic4.jpg','images/pic5.jpg']
верно

2022-04-15 17:34 UTC, BohdanPotapchuk commented on main.js
> +const a = ['images/pic1.jpg','images/pic2.jpg','images/pic3.jpg','images/pic4.jpg','images/pic5.jpg']
а что у нас в этом случае является "значение-заполнитель"
это с предадущий задачи (та что выше указана)

2022-04-17 09:48 UTC, stirgin commented on main.js
> +const a = ['images/pic1.jpg','images/pic2.jpg','images/pic3.jpg','images/pic4.jpg','images/pic5.jpg']
значение заполнитель эт то что будет подставлено вместо  selectedPic в 'images/pic${selectedPic}.jpg'

2022-04-17 13:23 UTC, BohdanPotapchuk commented on main.js
>    thumbBar.appendChild(newImage);
тоесть так ?
function createNewPic (selectedPic) {
  var newImage = document.createElement('img');
  newImage.setAttribute('src', `images/pic${selectedPic}.jpg`);
  thumbBar.appendChild(newImage);
}
Только не понимаю,куда передавать эту функцию так параметр

2022-04-17 15:07 UTC, stirgin commented on main.js
>    thumbBar.appendChild(newImage);
да так тоже подойдет

2022-04-17 15:08 UTC, stirgin commented on main.js
>    thumbBar.appendChild(newImage);
добавляй код, будем разбираться поэтапно, пока код в комментариях, мы картины не увидим целиком

2022-04-18 09:05 UTC, BohdanPotapchuk commented
добавил изменение в код

2022-04-18 10:28 UTC, BohdanPotapchuk commented on main.js
> +const a = ['images/pic1.jpg','images/pic2.jpg','images/pic3.jpg','images/pic4.jpg','images/pic5.jpg']
добавил изменение в код

2022-04-18 15:31 UTC, stirgin commented on main.js
> +var a = ['images/pic1.jpg','images/pic2.jpg','images/pic3.jpg','images/pic4.jpg','images/pic5.jpg'] ;
Для имен переменных используй более объясняющие их суть имена.
Объясни пожалуйста для чего тебе переменная b и a? На мой взгляд ты их можешь удалить из кода

2022-04-18 17:35 UTC, BohdanPotapchuk commented on main.js
> +var a = ['images/pic1.jpg','images/pic2.jpg','images/pic3.jpg','images/pic4.jpg','images/pic5.jpg'] ;
В принципе незачем . Удалил
Хочу розобратся какой код мне выполнять внутри цикла for

2022-04-20 09:52 UTC, stirgin commented on main.js
> +for(a = 1 ; a < 6 ; a++) {
переменная "a" все еще существует в цикле, замени ее на selectedPic

2022-04-20 09:53 UTC, stirgin commented on main.js
> +for(a = 1 ; a < 6 ; a++) {
добавь использование строгого режима в данном файле

2022-04-20 09:54 UTC, stirgin commented on main.js
> +for(a = 1 ; a < 6 ; a++) {
всегда указывай оператор объявление переменных var или let

2022-04-20 09:55 UTC, stirgin commented on main.js
> +var a = ['images/pic1.jpg','images/pic2.jpg','images/pic3.jpg','images/pic4.jpg','images/pic5.jpg'] ;
давай скорее, а то что-то завис на простом моменте, если что-т не понятно можем созвониться

2022-04-21 21:11 UTC, BohdanPotapchuk commented on main.js
> +for(a = 1 ; a < 6 ; a++) {
Сделал второй шаг
а конкретно клик по каждой мини картинке и вывод на большой екран
Но я не понял как сделать по примеру на саййте
но саму идею  думаю реализовал отлично
код работает без ошибок

2022-04-24 12:03 UTC, stirgin commented on main.js
> +var btn = document.querySelector('button');
Используй  const и let

2022-04-24 12:04 UTC, stirgin commented on main.js
> +var src = displayedImage.getAttribute('src');
Для чего тебе эта строка?

2022-04-24 12:07 UTC, stirgin commented on main.js
> +thumbBar.addEventListener('click', function(){
Событие выставлено на родительский элемент, сколько раз оно отрабатывает?

2022-04-24 17:21 UTC, BohdanPotapchuk commented on main.js
> +thumbBar.addEventListener('click', function(){
> Событие выставлено на родительский элемент, сколько раз оно отрабатывает?

нужно повесить событие на каждый елемент <img> ?

2022-04-26 11:09 UTC, stirgin commented on main.js
> +thumbBar.addEventListener('click', function(){
:) смотри, не писал про повесить событие на каждый элемент 
 задал вопрос, конкретно про то сколько раз у тебя отрабатывает хендлер при клике?


а вот вопрос. про повесить на каждый элемент, это уже тема для обсуждения, какой вариант по твоему мнению лучше, а какой хуже?

2022-05-01 13:26 UTC, BohdanPotapchuk commented on index.html
> +      </div>
text

2022-05-08 11:03 UTC, BohdanPotapchuk commented on main.js
> +thumbBar.addEventListener('click', function(){
доделал кнопки и запушил на репозиторий [c13bbce](https://github.com/BohdanPotapchuk/gallery-star/pull/1/commits/c13bbce8b1fc228957716a9b07f67766f8b3339d)

2022-05-25 11:56 UTC, stirgin commented
Можешь мержить PR, но не забудь добавить eslint для проверки и исправь все его замечания, на самом деле в данном проекте еще много моментов которые можно улучшить,  поэтому время от времени возвращайся к данному проекту.

2022-05-25 11:56 UTC, stirgin approved these changes

2022-06-26 12:42 UTC, merged